### ISSUE TITLE
missing file macros.h

### ISSUE THREAD

**Issue by michich** [prajnoha/sid#1]
Hello,

the build fails with:
```
make[1]: Entering directory '/home/michich/git/sid/resource'
  CC       libsidresource_la-ubridge.lo
In file included from ubridge.c:30:
../include/ubridge-cmd-module.h:23:10: fatal error: macros.h: No such file or directory
 #include "macros.h"
          ^~~~~~~~~~
compilation terminated.
```
commit 63d08774b03caae5efc6504c521b150e1d0c86b1 ("global: add macros.h with common macro definitions") added an ``#include "macros.h"``, but not the file itself.

**Comment by prajnoha** [comment]
Fixed with commit 2e90c6f5af0a3a9149f3e44f7b7038d11bb9b12a
